{
 "title": "Gestor de Incidentes",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Llamadas por minuto al gestor de incidentes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(experimento_1_data_total[1m]) * 60",
     "legendFormat": "{{exported_instance}}-{{method}}-{{path}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "Llamadas al gestor de incidentes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(experimento_1_data_total[1m]) * 60",
     "legendFormat": "{{exported_instance}}-{{method}}-{{path}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "Errores en llamadas por minuto al gestor de incidentes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(experimento_1_data_total{status_code=\"500\", exported_instance!=\"API GATEWAY\"}[1m]) * 60",
     "legendFormat": "{{exported_instance}}-{{method}}-{{path}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "Errores en Llamadas al gestor de incidentes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "increase(experimento_1_data_total{status_code=\"500\", exported_instance!=\"API GATEWAY\"}[1m]) * 60",
     "legendFormat": "{{exported_instance}}-{{method}}-{{path}}-{{status_code}}"
    }
   ]
  }
 ]
}